stages:
  - install
  - test
  - deploy

variables:
  DB_CONNECTION: mysql
  DB_HOST: "127.0.0.1"
  DB_PORT: "3306"
  DB_DATABASE: "laravel_ci"
  DB_USERNAME: "root"
  DB_PASSWORD: ""

before_script:
  - apt-get update -y
  - apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev
  - docker-php-ext-configure gd --with-freetype --with-jpeg
  - docker-php-ext-install gd

install_dependencies:
  stage: install
  image: php:8.2-fpm
  script:
    # Install Composer if it's not installed
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer install --no-interaction --prefer-dist
    - npm install
    - npm run dev
  only:
    - main

test:
  stage: test
  image: php:8.2-fpm
  script:
    - php artisan key:generate
    - php artisan migrate --env=testing
    - php artisan test
  only:
    - main

deploy:
  stage: deploy
  script:
    - echo "Deploying Laravel project"
    - rsync -avz --exclude 'node_modules/' --exclude '.git/' ./ gitlab.com/dd7_ysn/livraison
    - ssh git@gitlab.com:dd7_ysn/livraison.git && php artisan migrate --force && php artisan config:cache && php artisan route:cache'
  only:
    - main
